let OmniCpp_NamespaceSearch = 1
let OmniCpp_GlobalScopeSearch = 1
let OmniCpp_ShowAccess = 1
let OmniCpp_MayCompleteDot = 1
let OmniCpp_MayCompleteArrow = 1
let OmniCpp_MayCompleteScope = 1
let OmniCpp_DefaultNamespaces = ["std", "_GLIBCXX_STD"]

highlight clear
highlight Pmenu         ctermfg=0 ctermbg=2
highlight PmenuSel      ctermfg=0 ctermbg=7
highlight PmenuSbar     ctermfg=7 ctermbg=0
highlight PmenuThumb    ctermfg=0 ctermbg=7

" automatically open and close the popup menu / preview window
au CursorMovedI,InsertLeave * if pumvisible() == 0|silent! pclose|endif
set completeopt=menuone,menu,longest,preview

"inoremap <Nul> <C-n>
inoremap <Nul> <C-x><C-o>

